CFG/CFG/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('UKST.urls')),
]

CFG/UKST/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='UKST-home'),
    path('about/', views.about, name='UKST-about'),
]

CFG/UKST/models.py
from django.db import models

class SurveyResponse(models.Model):
    AGE_CHOICES = (
        ('0', '0-18'),
        ('1', '18-24'),
        ('2', '24-65'),
        ('3', '65+'),  
    )

    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )

    QUESTION_CHOICES = (
        ('Y', 'Yes'),
        ('N', 'No'),
    )

    age = models.CharField(max_length=1, choices=AGE_CHOICES)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    Q1 = models.CharField(max_length=1, choices=QUESTION_CHOICES)
    Q2 = models.CharField(max_length=1, choices=QUESTION_CHOICES)
    Q3 = models.CharField(max_length=1, choices=QUESTION_CHOICES)
    Q4 = models.CharField(max_length=1, choices=QUESTION_CHOICES)
    Q5 = models.CharField(max_length=1, choices=QUESTION_CHOICES)
    Q6 = models.CharField(max_length=1, choices=QUESTION_CHOICES)

    def __str__(self):
        return f"Age: {self.get_age_display()}, Gender: {self.get_gender_display()}"

CFG/UKST/forms.py
from django import forms
from .models import SurveyResponse

class SurveyForm(forms.ModelForm):
    ageChoices =  (
        ('0', '0-18'),
        ('1', '18-24'),
        ('2', '24-65'),
        ('3', '65+'),  
    )
    age = forms.ChoiceField(choices=ageChoices)

    genderChoices = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    gender = forms.ChoiceField(choices=genderChoices)
    
    q1Choices = (
        ('Y', 'Yes'),
        ('N', 'No'),
    )
    q1 = forms.ChoiceField(choices=q1Choices)
    
    q2Choices = (
        ('Y', 'Yes'),
        ('N', 'No'),
    )
    q2 = forms.ChoiceField(choices=q2Choices)
    
    q3Choices = (
        ('Y', 'Yes'),
        ('N', 'No'),
    )
    q3 = forms.ChoiceField(choices=q3Choices)
    
    q4Choices = (
        ('Y', 'Yes'),
        ('N', 'No'),
    )
    q4 = forms.ChoiceField(choices=q4Choices)
    
    q5Choices = (
        ('Y', 'Yes'),
        ('N', 'No'),
    )
    q5 = forms.ChoiceField(choices=q5Choices)
    
    q6Choices = (
        ('Y', 'Yes'),
        ('N', 'No'),
    )
    q6 = forms.ChoiceField(choices=q6Choices)

    class Meta:
        model = SurveyResponse
        fields = ['age', 'gender', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6']

CFG/UKST/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import SurveyForm
from .models import SurveyResponse

def home(request):
    if request.method == 'POST':
        form = SurveyForm(request.POST)
        if form.is_valid():
            # Create a SurveyResponse object with cleaned data
            survey_response = SurveyResponse(
                age=form.cleaned_data['age'],
                gender=form.cleaned_data['gender'],
                q1=form.cleaned_data['q1'],
                q2=form.cleaned_data['q2'],
                q3=form.cleaned_data['q3'],
                q4=form.cleaned_data['q4'],
                q5=form.cleaned_data['q5'],
                q6=form.cleaned_data['q6'],
            )
            # Save the object to the database
            survey_response.save()
            # Redirect to a success page or any other desired action
            return redirect('UKST-home')
    else:
        form = SurveyForm()
    return render(request, 'UKST/home.html', {'form': form})

def home(request):
    if request.method == 'POST':
        form = SurveyForm(request.POST)
        if form.is_valid():
            # Process the form data
            gender = form.cleaned_data['gender']
            age = form.cleaned_data['age']
            # Do something with the selected choice
            # add choice to database
            return render(request, 'UKST/home.html')#,{'gender': gender, 'age': age, }) #send to next page
    else:
        form = SurveyForm()
    return render(request, 'UKST/home.html',{'form': form})

def about(request):
    return render(request, 'UKST/about.html')

CFG/UKST/templates/UKST/about.html
{% extends "UKST/base.html" %}
{% block content%}
    <p>made by Team3</p>
{% endblock content %}

CFG/UKST/templates/UKST/base.html
{% load static%}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>UKST</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
        <!-- Nucleo Icons -->
        <link href="{% static '/assets/css/nucleo-icons.css' %}" rel="stylesheet" />
        <link href="{% static 'assets/css/nucleo-svg.css' %}" rel="stylesheet" />
        <!-- Font Awesome Icons -->
        <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
        <link href="{% static '/assets/css/nucleo-svg.css' %}" rel="stylesheet" />
        <!-- CSS Files -->
        <link id="pagestyle" href="{% static '/assets/css/soft-ui-dashboard.css' %}" rel="stylesheet" />
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand text-white"  style="font-size: 24px;" href="#">UKST</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'UKST-home'%}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'UKST-about'%}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Register</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

      {% block content %}{% endblock content%}

    <!--   Core JS Files   -->
    <script src="{% static '/assets/js/core/popper.min.js' %}"></script>
    <script src="{% static '/assets/js/core/bootstrap.min.js' %}"></script>

    <!-- Plugin for the charts, full documentation here: https://www.chartjs.org/ -->
    <script src="{% static '/assets/js/plugins/chartjs.min.js' %}"></script>
    <script src="{% static '/assets/js/plugins/Chart.extension.js' %}"></script>

    <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="{% static '/assets/js/soft-ui-dashboard.min.js' %}"></script>
    
    <!-- Regular Bootstrap5
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
    </body>
</html>

CFG/UKST/templates/UKST/form.html
<!DOCTYPE html>
<html>

    <div id="wrapper">
        <label for="yes_or_no">Are you experiencing slurred speech or confusion?</label>
      <p>
      <input type="radio" name="yes_no" checked>Yes</input>
      </p>
      <p>
      <input type="radio" name="yes_no">No</input>
      </p>
      </div>

      <div id="wrapper">
        <label for="yes_or_no">Are you experiencing extreme shivering or muscle pain?</label>
      <p>
      <input type="radio" name="yes_no" checked>Yes</input>
      </p>
      <p>
      <input type="radio" name="yes_no">No</input>
      </p>
      </div>

      <div id="wrapper">
        <label for="yes_or_no">Are you passing no urine in a day?</label>
      <p>
      <input type="radio" name="yes_no" checked>Yes</input>
      </p>
      <p>
      <input type="radio" name="yes_no">No</input>
      </p>
      </div>
       
      <div id="wrapper">
        <label for="yes_or_no">Do you have severe breathlessness?</label>
      <p>
      <input type="radio" name="yes_no" checked>Yes</input>
      </p>
      <p>
      <input type="radio" name="yes_no">No</input>
      </p>
      </div>

      <div id="wrapper">
        <label for="yes_or_no">Does it feel like you're going to die?</label>
      <p>
      <input type="radio" name="yes_no" checked>Yes</input>
      </p>
      <p>
      <input type="radio" name="yes_no">No</input>
      </p>
      </div>

      
      <div id="wrapper">
        <label for="yes_or_no">Is your skin mottled or discoloured?</label>
      <p>
      <input type="radio" name="yes_no" checked>Yes</input>
      </p>
      <p>
      <input type="radio" name="yes_no">No</input>
      </p>
      </div>

</html>

CFG/UKST/templates/UKST/genderselection/selectgender.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="selectgenderstyle.css">
    <title>Select Gender</title>
</head>

<header>
    <section class="heading">
        <div class="topnav">
            <a class="active" href="https://sepsistrust.org/">The UK Sepsis Trust</a>
        </div><br>
    </section>
 
<body>

    <a href="../infopage/index.html" class="back-button">Go Back</a>

    <h3>Choose your character to start on your self-assessment journey!</h3>
    
</body>

<div class="img-container">
    <div class="image">
      <img src="../images/F_youngadultbreathing.png" alt="Female">
      <a href="../sympton1.html">
        <button>Female</button>
      </a>
    </div>
    <div class="image">
      <img src="../images/M_youngadultbreathe.png" alt="Image 2">
      <div>
        <button>Male</button>
      </div>
    </div>
  </div>

<!-- Footer -->
<footer>
    <div class="container3">
        <div><a class="footerlink" href="https://sepsistrust.org/about/about-sepsis/faqs/" target="_blank">FaQ</a></div>
        <div><a class="footerlink" href="https://sepsistrust.org/privacy-policy/" target="_blank">Privacy Policy</a></div>
        <div><a class="footerlink" href="https://sepsistrust.org/terms-conditions/" target="_blank">Terms & Conditions</a></div>
        <div><a class="footerlink" href="https://sepsistrust.org/contact/" target="_blank">Contact Us</a></div>
    </div>
</footer>
</html>

CFG/UKST/templates/UKST/home.html
{% extends "UKST/base.html" %}
{% block content %}

    <!-- survey_form.html -->

<form method="post">
    {% csrf_token %}
    <div>
        <label for="id_age">Age:</label>
        {{ form.age }}
    </div>
    <div>
        <label for="id_gender">Gender:</label>
        {{ form.gender }}
    </div>
    <div>
        <label for="id_q1">Question 1:</label>
        {{ form.q1 }}
    </div>
    <div>
        <label for="id_q2">Question 2:</label>
        {{ form.q2 }}
    </div>
    <div>
        <label for="id_q3">Question 3:</label>
        {{ form.q3 }}
    </div>
    <div>
        <label for="id_q4">Question 4:</label>
        {{ form.q4 }}
    </div>
    <div>
        <label for="id_q5">Question 5:</label>
        {{ form.q5 }}
    </div>
    <div>
        <label for="id_q6">Question 6:</label>
        {{ form.q6 }}
    </div>
    <button type="submit">Submit</button>
</form>

{% endblock content %}

CFG/UKST/templates/UKST/infopage/index.html
<!DOCTYPE html>
<html>

<!-- Header -->

<link rel="stylesheet" href="infoPageStyle.css">

<head>
    <section class="heading">
        <div class="topnav">
            <a class="active" href="https://sepsistrust.org/">The UK Sepsis Trust</a>
        </div><br>
    </section>

<!-- Title -->
<center>
    <h1>
    Would you know if you or someone you know had Sepsis?
    </h1>
</center>
</head>

<!-- Container for the flexboxes -->

<!-- Left flexbox with the picture -->
<section class = "container">
<div class = "left">
    <img src="infopage_twochar.png" width="400" height="400" alt=''>
</div>

<!-- Right flexbox with description -->
<div class = "right">
    <h1> See your S.S.S </h1>
    <h3>
        (Sepsis Symptoms Score) 
    </h3> 
    <p>Welcome to our game where you will get the chance to learn more about Sepsis, </p >
    <p> including the symptons and how it can effect people of all ages. </p>
    <p> Click below to find out more!</p>
    
</div>

</section>

<!-- Play button -->
<div>
    <button class = "button" onclick="window.location.href = '../genderselection/selectgender.html';">Play!</button>
    <!-- <button onclick="alert('Starting game')">Play</button> -->
</div>
<!-- <div style = "position:relative; left:900px; top:-75px; padding: 10px;">
    <button class="button" onclick="alert('Starting game')" >Play</button>
 </div> -->

<!-- Footer -->
<footer>
    <div class="container3">
        <div><a class="footerlink" href="https://sepsistrust.org/about/about-sepsis/faqs/" target="_blank">FaQ</a></div>
        <div><a class="footerlink" href="https://sepsistrust.org/privacy-policy/" target="_blank">Privacy Policy</a></div>
        <div><a class="footerlink" href="https://sepsistrust.org/terms-conditions/" target="_blank">Terms & Conditions</a></div>
        <div><a class="footerlink" href="https://sepsistrust.org/contact/" target="_blank">Contact Us</a></div>
    </div>
</footer>
</html>

CFG/UKST/templates/UKST/last-page.html
<!DOCTYPE html>
<html>

<!-- Header -->

<link rel="stylesheet" href="infopage/infoPageStyle.css">

<head>
    <section class="heading">
        <div class="topnav">
            <a class="active" href="https://sepsistrust.org/">The UK Sepsis Trust</a>
        </div><br>
    </section>

<!-- Title -->
<center>
    <h1>   
    </h1>
</center>
</head>

<!-- Container for the flexboxes -->

<!-- Left flexbox with the picture -->
<section class = "container">
<div class = "left">
    <img src="images/lookingConcerned.jpg" width="400" height="400" style="margin-top: 40px;" alt=''>
</div>

<!-- Right flexbox with description -->
<div class = "right">
    <h1>You are experiencing 5/6 symptoms.</h1>
    <h3>
        There is a high chance you have sepsis. Here is what to do next.  
    </h3> 
    
    <p> Follow this link: </p>
    <a href="https://sepsistrust.org/get-support/">https://sepsistrust.org/get-support/</a>
    <p> Raise awareness. Save lives. </p>
    <a href="https://twitter.com/UKSepsisTrust">Twitter</a>
    <a href="https://www.facebook.com/TheUKSepsisTrust/">Facebook</a>
    <a href="https://www.youtube.com/user/TheUKSepsisTrust">Youtube</a>
    <a href="https://www.linkedin.com/company/uk-sepsis-trust/">LinkedIn</a>
    

</div>

</section>

<!-- Play button -->
<div>
    <button class = "button" onclick="window.location.href = '../UKST/last-page2.html'">Continue</button>
    <!-- <button onclick="alert('Starting game')">Play</button> -->
</div>
<!-- <div style = "position:relative; left:900px; top:-75px; padding: 10px;">
    <button class="button" onclick="alert('Starting game')" >Play</button>
 </div> -->

<!-- Footer -->
<footer>
    <div class="container3">
        <div><a class="footerlink" href="https://sepsistrust.org/about/about-sepsis/faqs/" target="_blank">FaQ</a></div>
        <div><a class="footerlink" href="https://sepsistrust.org/privacy-policy/" target="_blank">Privacy Policy</a></div>
        <div><a class="footerlink" href="https://sepsistrust.org/terms-conditions/" target="_blank">Terms & Conditions</a></div>
        <div><a class="footerlink" href="https://sepsistrust.org/contact/" target="_blank">Contact Us</a></div>
    </div>
</footer>
</html>

CFG/UKST/templates/UKST/last-page2.html
<!DOCTYPE html>
<html>

<!-- Header -->

<link rel="stylesheet" href="infopage/infoPageStyle.css">

<head>
    <section class="heading">
        <div class="topnav">
            <a class="active" href="https://sepsistrust.org/">The UK Sepsis Trust</a>
        </div><br>
    </section>

<!-- Title -->
<center>
    <h1>   
    </h1>
</center>
</head>

<!-- Container for the flexboxes -->

<!-- Left flexbox with the picture -->
<section class = "container">
<div class = "left">
    <img src="images/healthyGirl.png" width="400" height="400" style="margin-top: 40px;" alt=''>
</div>

<!-- Right flexbox with description -->
<div class = "right">
    <h1>You are experiencing 0/6 symptoms.</h1>
    <h3>
        There is a low chance you have sepsis. You can still learn about it..  
    </h3> 
    
    <p> Follow this link: </p>
    <a href="https://sepsistrust.org/get-support/">https://sepsistrust.org/get-support/</a>
    <p> Raise awareness. Save lives. </p>
    <a href="https://twitter.com/UKSepsisTrust">Twitter</a>
    <a href="https://www.facebook.com/TheUKSepsisTrust/">Facebook</a>
    <a href="https://www.youtube.com/user/TheUKSepsisTrust">Youtube</a>
    <a href="https://www.linkedin.com/company/uk-sepsis-trust/">LinkedIn</a>
    

</div>

</section>

<!-- Play button -->
<div>
    <button class = "button" onclick="window.location.href = '../UKST/infopage/index.html'">Start again</button>
    <!-- <button onclick="alert('Starting game')">Play</button> -->
</div>
<!-- <div style = "position:relative; left:900px; top:-75px; padding: 10px;">
    <button class="button" onclick="alert('Starting game')" >Play</button>
 </div> -->

<!-- Footer -->
<footer>
    <div class="container3">
        <div><a class="footerlink" href="https://sepsistrust.org/about/about-sepsis/faqs/" target="_blank">FaQ</a></div>
        <div><a class="footerlink" href="https://sepsistrust.org/privacy-policy/" target="_blank">Privacy Policy</a></div>
        <div><a class="footerlink" href="https://sepsistrust.org/terms-conditions/" target="_blank">Terms & Conditions</a></div>
        <div><a class="footerlink" href="https://sepsistrust.org/contact/" target="_blank">Contact Us</a></div>
    </div>
</footer>
</html>

CFG/UKST/templates/UKST/symptom2.html
<!DOCTYPE html>
<html>

<!-- Header -->

<link rel="stylesheet" href="infopage/infoPageStyle.css">

<head>
    <section class="heading">
        <div class="topnav">
            <a class="active" href="https://sepsistrust.org/">The UK Sepsis Trust</a>
        </div><br>
    </section>

<!-- Title -->
<center>
    <h1>
    </h1>
</center>
</head>

<!-- Container for the flexboxes -->

<a href="../UKST/genderselection/selectgender.html" class="back-button">Go Back</a>

<!-- Left flexbox with the picture -->
<section class = "container">
<div class = "left">
    <img src="images/F_youngadultthought.png" width="400" height="400" style="margin-top: 40px;" alt=''>
</div>

<!-- Right flexbox with description -->
<div class = "right">
    <h1> It feels like you're going to die</h1>
    <h3>
        Overwhelming sense of fear or panic. Feels like your life is in danger. 
    </h3> 
    
    <div id="wrapper">
        <label for="yes_or_no">Does it feel like you're going to die?</label>
      <p>
      <input type="radio" name="yes_no" checked>Yes</input>
      </p>
      <p>
      <input type="radio" name="yes_no">No</input>
      </p>
      </div>
   
</div>

</section>

<!-- Play button -->
<div>
    <button class = "button" onclick="window.location.href = '../UKST/last-page.html';">Continue</button>
    <!-- <button onclick="alert('Starting game')">Play</button> -->
</div>
<!-- <div style = "position:relative; left:900px; top:-75px; padding: 10px;">
    <button class="button" onclick="alert('Starting game')" >Play</button>
 </div> -->

<!-- Footer -->
<footer>
    <div class="container3">
        <div><a class="footerlink" href="https://sepsistrust.org/about/about-sepsis/faqs/" target="_blank">FaQ</a></div>
        <div><a class="footerlink" href="https://sepsistrust.org/privacy-policy/" target="_blank">Privacy Policy</a></div>
        <div><a class="footerlink" href="https://sepsistrust.org/terms-conditions/" target="_blank">Terms & Conditions</a></div>
        <div><a class="footerlink" href="https://sepsistrust.org/contact/" target="_blank">Contact Us</a></div>
    </div>
</footer>
</html>

CFG/UKST/templates/UKST/sympton1.html
<!DOCTYPE html>
<html>

<!-- Header -->

<link rel="stylesheet" href="infopage/infoPageStyle.css">

<head>
    <section class="heading">
        <div class="topnav">
            <a class="active" href="https://sepsistrust.org/">The UK Sepsis Trust</a>
        </div><br>
    </section>

<!-- Title -->
<center>
    <h1>
    </h1>
</center>
</head>

<!-- Container for the flexboxes -->

<a href="../UKST/genderselection/selectgender.html" class="back-button">Go Back</a>

<!-- Left flexbox with the picture -->
<section class = "container">
<div class = "left">
    <img src="images/F_youngadultmouth.png" width="400" height="400" style="margin-top: 40px;" alt=''>
</div>

<!-- Right flexbox with description -->
<div class = "right">
    <h1> Slurred speech or confusion</h1>
    <h3>
        Trouble speaking clearly and getting confused at the simplest things. 
    </h3> 
    
    <div id="wrapper">
        <label for="yes_or_no">Are you experiencing slurred speech or confusion?</label>
      <p>
      <input type="radio" name="yes_no" checked>Yes</input>
      </p>
      <p>
      <input type="radio" name="yes_no">No</input>
      </p>
      </div>
   
    
</div>

</section>

<!-- Play button -->
<div>
    <button class = "button" onclick="window.location.href = '../UKST/symptom2.html'">Continue</button>
    <!-- <button onclick="alert('Starting game')">Play</button> -->
</div>
<!-- <div style = "position:relative; left:900px; top:-75px; padding: 10px;">
    <button class="button" onclick="alert('Starting game')" >Play</button>
 </div> -->

<!-- Footer -->
<footer>
    <div class="container3">
        <div><a class="footerlink" href="https://sepsistrust.org/about/about-sepsis/faqs/" target="_blank">FaQ</a></div>
        <div><a class="footerlink" href="https://sepsistrust.org/privacy-policy/" target="_blank">Privacy Policy</a></div>
        <div><a class="footerlink" href="https://sepsistrust.org/terms-conditions/" target="_blank">Terms & Conditions</a></div>
        <div><a class="footerlink" href="https://sepsistrust.org/contact/" target="_blank">Contact Us</a></div>
    </div>
</footer>
</html>